### PR TITLE
Fix/context menu

### LINKED ISSUE #89: Context menu positioning
> _A context menu!_

bx6SJjbEWr

The current organization of the apostrophe 3 front-end makes it difficult to position a context menu in all the ways you'd naturally expect.

Ideally a context menu would:
- Remain attached to its parent while scrolling
- Appear above all sibling UI
- Not be clipped by overflow settings

As a tidy Vue component it should also be bundled with its button for a direct line of communication when toggling its opened/closed state.

The current implementation is a fussy calculation of the exact X,Y position on the page and having the element `position: fixed`. This breaks down when a user scrolls (and with the multiple scroll contexts of a modal is even more fussy to try to correct on scroll).

> Why not go absolute from the start?

Absolute provided its own challenges, like improper sibling z-index layering and context menu ui being clipped by the enforced individual scroll contexts of the apostrophe modals.
image

> _whoops, where'd the tag interface go?_

Looking for suggestions from @abea @gregvanbrug @breyell @falkodev 

Component located in `src/components/contextMenu/AposContextMenu.vue`

### PR DESCRIPTION
**Pull request by abea**
Since storybook isn't in core yet, and might not be for a few days, I want to keep this moving in here.

This solves issues around scrolling (big one), z-index, and auto-closing. The remaining issue is specifically in Media Manager, where a wider context menu (like AposTagApply) can get cut off due to the overflow on small-ish screens. I'm talking tablet-width, where we're going to have a lot of things to figure out anyway. I suggest we go with this approach and work out the tablet experience along with other elements of that view later (hopefully not too much later).

Closes #89

### CODE REVIEW

File: src/components/contextMenu/AposContextMenu.vue [hunk 1]
```diff
@@ -105,26 +111,25 @@ export default {
     },
     buttonState() {
       return this.open ? ['active'] : null;
+    },
+    localCssVar() {
+      // Set the CSS custom property for this specific context menu.
+      return { '--tip-width': `${this.tipWidth}px` };
```
Comment (abea) [inline src/components/contextMenu/AposContextMenu.vue:117]: At the moment, this is always the same everywhere. We could make this a global variable nice an easy, though that doesn't help with the need to have the value handy for passing into the tip component. ... Or we go with magic numbers in the tip component and here (see line 202) and don't worry about the connection.

File: src/components/mediaManager/AposMediaManager.vue [hunk 2]
```diff
@@ -238,6 +239,12 @@ export default {
 
 <style lang="scss" scoped>
 @import '../../scss/_mixins';
+
+  .apos-media-manager /deep/ .apos-media-manager-toolbar {
+    position: relative;
+    z-index: 3;
```
Comment (abea) [inline src/components/mediaManager/AposMediaManager.vue:245]: In core, z-index is handled through global variables. I foresee resolving this floating number there.
