### PR TITLE
closes #13. notifications.

### LINKED ISSUE #13: Notifications
image

States
- Success
- Fail
- Information
- Warning

### PR DESCRIPTION
**Pull request by grdunn**

### CODE REVIEW

**Comment by grdunn** [comment]
@stuartromanek looking for guidance around how to best handle the background color change from light to dark mode (wrapper class? are we pushing both styles for this?)

File: src/components/notification/notification.vue [hunk 1]
```diff
@@ -17,7 +17,8 @@ module.exports = {
     modifier: {
       default: '',
       type: String
-    }
+    },
+    clickable: Boolean
```
Comment (stuartromanek) [inline src/components/notification/notification.vue]: give this a default

**Comment by grdunn** [comment]
👍
